---
- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Restart left4dead2
  service:
    name: left4dead2
    state: restarted
  listen: "Restart source games"

- name: Stop left4dead2
  service:
    name: left4dead2
    state: stopped
  listen: "Stop source games"
